// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vlbmevkngtvefionrkvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsYm1ldmtuZ3R2ZWZpb25ya3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzcwNzYsImV4cCI6MjA2NjQxMzA3Nn0.qN7LeacOPalR3f2iyXFMIAMJIjyxDeFhvbNgfTxpOxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);